version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # prevent overwriting node_modules with host
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # helps with live reload inside Docker
    networks:
      - attendance-network


  attendance-backend:
    build: ./attendance-backend
    container_name: attendance-backend
    ports:
      - "8000:80"
    volumes:
      - ./attendance-backend/src:/var/www/html
    depends_on:
      - attendance-db
    environment:
      - DB_HOST=attendance-db
      - DB_NAME=attendance_system
      - DB_USER=root
      - DB_PASSWORD=secret
    networks:
      - attendance-network

  attendance-db:
    image: mysql:8.0
    container_name: attendance-db
    ports:
      - "3307:3306"  # Different port than default MySQL to avoid conflicts
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=attendance
    volumes:
      - ./attendance-backend/sql:/docker-entrypoint-initdb.d
      - attendance-db-data:/var/lib/mysql
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  attendance-db-data: