services:
  mysql:
    image: mysql:8.0
    container_name: cashier-mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashier_db
      MYSQL_USER: cashieruser
      MYSQL_PASSWORD: cashierpass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cashier-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cashier-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8087:80"
    depends_on:
      - mysql
    networks:
      - cashier-network

  cashier-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashier-backend
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=cashier_db
      - DB_USER=cashieruser
      - DB_PASSWORD=cashierpass
    networks:
      - cashier-network

volumes:
  mysql_data:

networks:
  cashier-network:
    driver: bridge 